### ISSUE TITLE
NullReferenceException in setup

### ISSUE THREAD

**Issue by radissoa** [semiodesk/modom-support#14]
Hello,

I get this message after the click on Done when the github connection has been made : 

modom-io_1  | fail: Microsoft.AspNetCore.Server.Kestrel[13]
modom-io_1  |       Connection id "0HM094D100S3S", Request id "0HM094D100S3S:0000000F": An unhandled exception was thrown by the application.
modom-io_1  | System.NullReferenceException: Object reference not set to an instance of an object.
modom-io_1  |    at Modom.External.FederationService.UpdateFederatedAccountDataAsync(UserInfo user, String connectedAccount) in /src/backend/modules/external/services/FederationService.cs:line 91
modom-io_1  |    at Modom.OnPremise.Services.AuthService.TryCreateAdminUser(String name, String emailAddress, String username, String password, String organization, String photo, String connectedAccounts, Dictionary`2 attributes) in /src/backend/modules/on-premise/services/AuthService.cs:line 255
modom-io_1  |    at Modom.Controllers.admin.SetupController.Setup(UserParameters user) in /src/backend/modules/setup/controllers/SetupController.cs:line 31
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
modom-io_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
modom-io_1  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
modom-io_1  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
modom-io_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
modom-io_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

BR,
Alexis

**Comment by meberl** [comment]
Additional error output was added to make it easier to track the cause of problems.
